# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0010_auto_20170107_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='last_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
