# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0012_lastpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastpage',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
