# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0013_auto_20180217_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='last_page',
        ),
        migrations.AddField(
            model_name='lastpage',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_page', to='comic.Comic'),
        ),
    ]
