# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0014_auto_20180217_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='lastpage',
            name='comic',
        ),
        migrations.AddField(
            model_name='comic',
            name='last_page',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='LastPage',
        ),
        migrations.AddField(
            model_name='comicmanager',
            name='comic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comic_manager', to='comic.Comic'),
        ),
    ]
