# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-17 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0015_auto_20180217_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicmanager',
            name='comic',
        ),
        migrations.AddField(
            model_name='comicmanager',
            name='last_page',
            field=models.IntegerField(default=1),
        ),
    ]
